### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Sod-Almighty** [mmichaa/passafari.safariextension#10]
I see no way to install this, and there are no instructions. Renaming the zipfile to safariextz doesn't help. What a complete and utter waste of my valuable time.

**Comment by DeeeeLAN** [comment]
On the code tab of the project, click releases (it is two buttons over) from there you can download the latest release.

**Comment by Sod-Almighty** [comment]
Thanks. But that doesn't work either. It still doesn't show up in the Safari extensions list after launching the extension (or dragging it into Safari).

Do I need to restart Safari? And if so, why does it not say this?

**Comment by DeeeeLAN** [comment]
You definitely downloaded the .safariextz file right? Try dragging it into the extensions window in preferences.

**Comment by mmichaa** [comment]
> What a complete and utter waste of my valuable time.

lul

thanks again, @avidmills, for your help!
does it work for you now, @Sod-Almighty?

**Comment by Sod-Almighty** [comment]
I tried those things. It doesn't show up in the extensions window.

**Comment by DeeeeLAN** [comment]
Are you running the most recent version of safari? Is there a security setting preventing you from installing plugins from outside the safari plugins directory?

**Comment by Sod-Almighty** [comment]
I'm using Safari 9.1.2. I don't see any settings preventing me from installing plugins. I had a look at the Security tab of the Preferences, but don't see anything relevant. If such a setting exists, then it's certainly not easy to find.

**Comment by DeeeeLAN** [comment]
Upgrade to safari 10 (10.0.1) and try again. I believe safari 10 is where
support was added.

**Comment by DeeeeLAN** [comment]
This issue can now be closed.

**Comment by Sod-Almighty** [comment]
No it can't. I don't have the option to upgrade to Safari 10. Why isn't version 9 supported?

**Comment by DeeeeLAN** [comment]
It looks like the

~/Library/Safari/Extensions

folder has both the .safariextz files and a plist of installed extensions.
To install it "manually" you could try dropping the .safariextz file in
there and adding a plist entry in Xcode. Then you would have to restart
Safari (or maybe even logout) for the changes to take effect.

It is impractical to continue supporting an older version of safari when
the newest version provides easy support. If you are unable to update, you
will need to figure out how to install, or what is causing a conflict.
Google "can't install extension safari 9" or something along those lines.
Without having safari 9 to test on, there isn't much we can do.
