### ISSUE TITLE
How do we set it up?

### ISSUE THREAD

**Issue by BoogieUpps** [mmichaa/passafari.safariextension#2]
I apologize if I'm missing something obvious, but the extension doesn't seem to work on Safari 8.0.6. for me. I do get a new entry in KeePassHttp Settings, but the fields remain empty or get filled from Apple Keychain. I noticed that you can tweak a few settings (Hostname, Port, etc.), so what do we put in those fields? And does it even work on 8.0.6? 
Cheers

**Comment by moesby** [comment]
Same issue here. I also have established the connection between Safari and KeePass but nothing happens if a URL is opened. KeePassHttp works fine with chrome or mozilla. Can I provide any helpful information like log files etc.?
cheers

**Comment by mmichaa** [comment]
Hello @BoogieUpps and @moesby, sorry for my late response. It works for me on Safari 8.0.7. Settings must not be set, the defaults _(used if empty; not visible)_ should work in most cases. Maybe it's an usage issue:
I use KeePassHttp on Chrome and Firefox too. I know, that there appears an key icon on input fields. That **doesn't** happen here in Safari _(yet)_. You always have to hit the KeePass icon in Safari after the page is loaded. Does this help you?

**Comment by BoogieUpps** [comment]
First of all, thank you for your work. The thing that helped me was setting URL-Format and Submit-URL-Format to Full. Not sure if it is the default that I messed up earlier or not, but it worked. Keep up the good work!
