### ISSUE TITLE
Host match does not work

### ISSUE THREAD

**Issue by Lich4r** [mmichaa/passafari.safariextension#7]
Hi,

When I go the a login page and click on passafari button it displays every entry I have in the database, instead of only the one matching the url/host

**Comment by mmichaa** [comment]
Hi @FromBabylon, I had the same problem using passafari with MacPass. Could you try it again with the URL-Format on "Protocol & Host" setting? It solved the issue for me. If it doesn't solve the issue for you, could you please give me more informations? Like website url, if you are using macpass or kypass companion, version, etc. Thanks!

**Comment by Lich4r** [comment]
Hi @mmichaa,

It worked ! I already tried this but guess I had to lock/unlock the database to make it work

Thanks
