### ISSUE TITLE
File support in addition to the existing KeePassHttp support

### ISSUE THREAD

**Issue by cemmersb** [mmichaa/passafari.safariextension#8]
Hello!
Looking at the project, I was wondering if it is feasible to add some plain file support for e.g. *.kdbx files to the existing KeePassHttp support. This would allow me to add an existing database file locally, without the need of installing an HTTP server.

<img width="543" alt="screen shot 2016-03-21 at 6 29 42 am" src="https://cloud.githubusercontent.com/assets/1866870/13920133/ab0f2246-ef2e-11e5-917c-286372aea6ce.png">

Thank's for all the effort, the plugin itself looks really great!

**Comment by mmichaa** [comment]
I currently have no plans to add plain file support. I think, I will never add this. Sorry 😕
